import {inYear,num} from './utils.js';
export const inventoryCost=inv=>num(inv?.costPrice);
export function saleProfit(sale,inventory=null){const cost=num(sale.costPrice||inventory?.costPrice||0),gross=num(sale.grossPrice),fee=num(sale.fee),shipping=num(sale.shipping),extra=num(sale.extraCost);const netReceipt=gross-fee-shipping,profit=gross-fee-shipping-cost-extra,margin=gross?profit/gross*100:0;return{gross,fee,shipping,extra,cost,netReceipt,profit,margin}}
export function calcMaterialAverageCost(data,materialId){const ps=data.materialPurchases.filter(p=>p.materialId===materialId);const q=ps.reduce((s,p)=>s+num(p.qty),0),a=ps.reduce((s,p)=>s+num(p.amount),0);return q>0?a/q:0}
export function materialConsumedQty(data,materialId){return data.productionBatches.reduce((sum,b)=>sum+(b.consumedMaterials||[]).filter(c=>c.materialId===materialId).reduce((s,c)=>s+num(c.qty),0),0)}
export const materialPurchasedQty=(data,id)=>data.materialPurchases.filter(p=>p.materialId===id).reduce((s,p)=>s+num(p.qty),0);
export const materialStock=(data,id)=>materialPurchasedQty(data,id)-materialConsumedQty(data,id);
export function recipeEstimatedUnitCost(data,recipe){return(recipe?.components||[]).reduce((sum,c)=>sum+calcMaterialAverageCost(data,c.materialId)*num(c.qty),0)}
export function calcProductionPlan(data,recipe,outputQty,directCost=0){const out=Math.max(1,num(outputQty)||1);const consumedMaterials=(recipe?.components||[]).map(c=>{const qty=num(c.qty)*out,unitCost=calcMaterialAverageCost(data,c.materialId),amount=qty*unitCost;return{materialId:c.materialId,qty,unitCost,amount}});const materialCost=consumedMaterials.reduce((s,c)=>s+c.amount,0),totalCost=materialCost+num(directCost),unitCost=out?totalCost/out:0;return{consumedMaterials,materialCost,totalCost,unitCost}}
export function calcSummary(data,period='all',year=new Date().getFullYear()){const by=Object.fromEntries(data.inventories.map(i=>[i.id,i]));const sales=data.sales.filter(s=>period==='all'||inYear(s.soldAt,year));const expenses=data.expenses.filter(e=>period==='all'||inYear(e.date,year));const calcs=sales.map(s=>saleProfit(s,by[s.inventoryId]));const salesTotal=calcs.reduce((s,c)=>s+c.gross,0),costTotal=calcs.reduce((s,c)=>s+c.cost,0),feeTotal=calcs.reduce((s,c)=>s+c.fee,0),shippingTotal=calcs.reduce((s,c)=>s+c.shipping,0),extraTotal=calcs.reduce((s,c)=>s+c.extra,0),expenseTotal=expenses.reduce((s,e)=>s+num(e.amount),0),profit=calcs.reduce((s,c)=>s+c.profit,0)-expenseTotal,margin=salesTotal?profit/salesTotal*100:0;return{salesCount:sales.length,salesTotal,costTotal,feeTotal,shippingTotal,extraTotal,expenseTotal,profit,margin}}
export function inventoryValueAtYearEnd(data,year){const soldIds=new Set(data.sales.filter(s=>s.soldAt&&String(s.soldAt)<=`${year}-12-31`).map(s=>s.inventoryId));return data.inventories.filter(i=>!soldIds.has(i.id)).reduce((s,i)=>s+inventoryCost(i)*(num(i.quantity)||1),0)}
